#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@File    :   corewords.py
@Time    :   2019/03/26 11:00:04
@Author  :   Hzx 
@Version :   1.0
@Contact :   hzxstarcloud@hotmail.com
@Desc    :   Store keywords for 
'''

# here put the import lib
corewords = {
    'CHINESE' : ("中德关系",r"中英关系",r"中法关系",r"中欧关系",r"中德合作",r"中法合作",r"中英合作",r"中俄合作",r"中欧合作",r"中国与欧洲",r"中国与欧盟",r"中国与中东欧",r"中国与德国",r"中国与英国",r"中国与法国",r"一带一路",r"17+1"),

    'ENGLISH' : (r"\bGerman-Chinese relations\b",r"\bSino-German relations\b",r"\bChinese-German relations\b",r"\bGerman-Sino relations\b",r"\bRelations between China and Germany\b",r"\bRelations between Germany and China\b",r"\bRelations between the People's Republic of China and Germany\b",r"\bRelations between Germany and the PRC\b",r"\bCooperation between Germany and China\b",r"\bCooperation between China and Germany\b",r"\bGermany and China\b",r"\bChina and Germany\b",r"\bFrench-Chinese relations\b",r"\bSino-French relations\b",r"\bFrench-Sino relations\b",r"\bSino-French relations\b",r"\bRelations between China and France\b",r"\bRelations between France and China\b",r"\bRelations between the PRC and France\b",r"\bRelations between France and the PRC\b",r"\bCooperation between France and China\b",r"\bCooperation between China and France\b",r"\bFrance and China\b",r"\bChina and France\b",r"\bEnglish-Chinese relations\b",r"\bSino-English relations\b",r"\bEnglish-Sino relations\b",r"\bSino-English relations\b",r"\bRelations between China and the UK\b",r"\bRelations between the UK and China\b",r"\bRelations between the PRC and the UK\b",r"\bRelations between the UK and the PRC\b",r"\bCooperation between the UK and China\b",r"\bCooperation between China and the UK\b",r"\bBritain and China\b",r"\bChina and the UK\b",r"\bEuropean-Chinese relations\b",r"\bSino-European relations\b",r"\bEuropean-Sino relations\b",r"\bSino-European relations\b",r"\bRelations between China and the EU\b",r"\bRelations between the EU and China\b",r"\bRelations between the PRC and the EU\b",r"\bRelations between the EU and the PRC\b",r"\bCooperation between the EU and China\b",r"\bCooperation between China and the EU\b",r"\bEurope and China\b",r"\bChina and Europe\b",r"\bEuropean Union and China\b",r"\bChina and European Union\b",r"\b17 + 1\b",r"\bOne Belt One Road\b",r"\bThe Belt and Road\b",r"\bSilk Road\b",r"\bSilk Road Economic Belt\b",r"\bMaritime Silk Road\b"),

    'GERMAN' : (r"\bdeutsch-chinesische Beziehungen\b",r"\bsino-deutsche Beziehungen\b",r"\bchinesisch-deutsche Beziehungen\b",r"\bdeutsch-sino Beziehungen\b",r"\bBeziehungen zwischen China und Deutschland\b",r"\bBeziehungen zwischen Deutschland und China\b",r"\bBeziehungen zwischen der VR China und der Bundesrepublik\b",r"\bBeziehungen zwischen der Bundesrepublik und der VR China\b",r"\bZusammenarbeit zwischen Deutschland und China\b",r"\bZusammenarbeit zwischen China und Deutschland\b",r"\bDeutschland und China\b",r"\bChina und Deutschland\b",r"französisch-chinesische Beziehungen\b",r"\bchinesisch-französische Beziehungen\b",r"\bfranzösisch-sino Beziehungen\b",r"\bsino-französische Beziehungen\b",r"\bBeziehungen zwischen China und Frankreich\b",r"\bBeziehungen zwischen Frankreich und China\b",r"\bBeziehungen zwischen der VR China und Frankreich\b",r"\bBeziehungen zwischen Frankreich und der VR China\b",r"\bZusammenarbeit zwischen Frankreich und China\b",r"\bZusammenarbeit zwischen China und Frankreich\b",r"\bFrankreich und China\b",r"\bChina und Frankreich\b",r"\benglisch-chinesische Beziehungen\b",r"\bchinesisch-englische Beziehungen\b",r"\benglisch-sino Beziehungen\b",r"\bsino-englische Beziehungen\b",r"\bBeziehungen zwischen China und Großbritannien\b",r"\bBeziehungen zwischen Großbritannien und China\b",r"\bBeziehungen zwischen der VR China und Großbritannien\b",r"\bBeziehungen zwischen Großbritannien und der VR China\b",r"\bZusammenarbeit zwischen Großbritannien und China\b",r"\bZusammenarbeit zwischen China und Großbritannien\b",r"\bGroßbritannien und China\b",r"\bChina und Großbritannien\b",r"\beuropäisch-chinesische Beziehungen\b",r"\bchinesisch-europäische Beziehungen\b",r"\beuropäisch-sino Beziehungen\b",r"\bsino-europäische Beziehungen\b",r"\bBeziehungen zwischen China und der EU\b",r"\bBeziehungen zwischen der EU und China\b",r"\bBeziehungen zwischen der VR China und der EU\b",r"\bBeziehungen zwischen der EU und der VR China\b",r"\bZusammenarbeit zwischen der EU und China\b",r"\bZusammenarbeit zwischen China und der EU\b",r"\bEuropa und China\b",r"\bChina und Europa\b",r"\bEuropäische Union und China\b",r"\bChina und Europäische Union\b",r"\b17 + 1\b",r"\bOne Belt One Road\b",r"\b\b",r"\bEin Band, Eine Straße\b",r"\bSeidenstraße\b",r"\bSilk Road Economic Belt\b",r"\bMaritime Silk Road\b")
}