#!/usr/bin/env python3
# encoding: utf-8

"""
@version: 1.0
@author: rym
@file: V2_corewords.py
@time: 2020/3/13 17:53
"""


corewords = {
    'CHINESE' : ("中德关系",r"中英关系",r"中法关系",r"中欧关系",r"中德合作",r"中法合作",r"中英合作",r"中俄合作",r"中欧合作",r"中国与欧洲",r"中国与欧盟",r"中国与中东欧",r"中国与德国",r"中国与英国",r"中国与法国",r"一带一路",r"17+1"),

    'ENGLISH' : (r"German-Chinese relations",r"Sino-German relations",r"Chinese-German relations",r"German-Sino relations",r"Relations between China and Germany",r"Relations between Germany and China",r"Relations between the People's Republic of China and Germany",r"Relations between Germany and the PRC",r"Cooperation between Germany and China",r"Cooperation between China and Germany",r"Germany and China",r"China and Germany",r"French-Chinese relations",r"Sino-French relations",r"French-Sino relations",r"Sino-French relations",r"Relations between China and France",r"Relations between France and China",r"Relations between the PRC and France",r"Relations between France and the PRC",r"Cooperation between France and China",r"Cooperation between China and France",r"France and China",r"China and France",r"English-Chinese relations",r"Sino-English relations",r"English-Sino relations",r"Sino-English relations",r"Relations between China and the UK",r"Relations between the UK and China",r"Relations between the PRC and the UK",r"Relations between the UK and the PRC",r"Cooperation between the UK and China",r"Cooperation between China and the UK",r"Britain and China",r"China and the UK",r"European-Chinese relations",r"Sino-European relations",r"European-Sino relations",r"Sino-European relations",r"Relations between China and the EU",r"Relations between the EU and China",r"Relations between the PRC and the EU",r"Relations between the EU and the PRC",r"Cooperation between the EU and China",r"Cooperation between China and the EU",r"Europe and China",r"China and Europe",r"European Union and China",r"China and European Union",r"17 + 1",r"One Belt One Road",r"The Belt and Road",r"Silk Road",r"Silk Road Economic Belt",r"Maritime Silk Road"),

    'GERMAN' : (r"deutsch-chinesische Beziehungen",r"sino-deutsche Beziehungen",r"chinesisch-deutsche Beziehungen",r"deutsch-sino Beziehungen",r"Beziehungen zwischen China und Deutschland",r"Beziehungen zwischen Deutschland und China",r"Beziehungen zwischen der VR China und der Bundesrepublik",r"Beziehungen zwischen der Bundesrepublik und der VR China",r"Zusammenarbeit zwischen Deutschland und China",r"Zusammenarbeit zwischen China und Deutschland",r"Deutschland und China",r"China und Deutschland",r"französisch-chinesische Beziehungen",r"chinesisch-französische Beziehungen",r"französisch-sino Beziehungen",r"sino-französische Beziehungen",r"Beziehungen zwischen China und Frankreich",r"Beziehungen zwischen Frankreich und China",r"Beziehungen zwischen der VR China und Frankreich",r"Beziehungen zwischen Frankreich und der VR China",r"Zusammenarbeit zwischen Frankreich und China",r"Zusammenarbeit zwischen China und Frankreich",r"Frankreich und China",r"China und Frankreich",r"englisch-chinesische Beziehungen",r"chinesisch-englische Beziehungen",r"englisch-sino Beziehungen",r"sino-englische Beziehungen",r"Beziehungen zwischen China und Großbritannien",r"Beziehungen zwischen Großbritannien und China",r"Beziehungen zwischen der VR China und Großbritannien",r"Beziehungen zwischen Großbritannien und der VR China",r"Zusammenarbeit zwischen Großbritannien und China",r"Zusammenarbeit zwischen China und Großbritannien",r"Großbritannien und China",r"China und Großbritannien",r"europäisch-chinesische Beziehungen",r"chinesisch-europäische Beziehungen",r"europäisch-sino Beziehungen",r"sino-europäische Beziehungen",r"Beziehungen zwischen China und der EU",r"Beziehungen zwischen der EU und China",r"Beziehungen zwischen der VR China und der EU",r"Beziehungen zwischen der EU und der VR China",r"Zusammenarbeit zwischen der EU und China",r"Zusammenarbeit zwischen China und der EU",r"Europa und China",r"China und Europa",r"Europäische Union und China",r"China und Europäische Union",r"17 + 1",r"One Belt One Road",r"The Belt and Road",r"Ein Band, Eine Straße",r"Seidenstraße",r"Silk Road Economic Belt",r"Maritime Silk Road")
}